- name: copy MetalLB manifests
  become: true
  template:
    src: metallb.yaml
    dest: /etc/metallb.yaml

- name: copy MetalLB config
  become: true
  template:
    src: metallb-config.yaml
    dest: /etc/metallb-config.yaml

- name: create namespace
  become: true
  command: kubectl create namespace metallb-system --kubeconfig=/etc/kubernetes/admin.conf

- name: install MetalLB config
  become: true
  command: kubectl apply -f /etc/metallb-config.yaml --kubeconfig=/etc/kubernetes/admin.conf

- name: install MetalLB
  become: true
  command: kubectl apply -f /etc/metallb.yaml --kubeconfig=/etc/kubernetes/admin.conf
