- name: install common packages
  become: true

  apt:
    pkg:
      - apt-transport-https
      - curl
    update_cache: yes

- name: disable swap
  become: true

  command: swapoff -a

- name: disable swap in fstab
  become: true

  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'

- name: enable br_netfilter
  become: true
  command: modprobe br_netfilter

- name: ensure iptables enabled
  become: true

  template:
    src: k8s.iptables.conf
    dest: /etc/sysctl.d/k8s.iptables.conf

- name: enable port forward
  become: true

  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    reload: yes
